version: "3.9"
services:
  mongodb:
    container_name: recipe-mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27015:27017"
    volumes:
      - mongodb-data:/data/db
      # - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    env_file:
      - .env
    command: [ --auth ]
volumes:
  mongodb-data:
