version: "3.9"
services:
  mongodb:
    container_name: recipe-mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27015:27017"
    volumes:
      - mongodb-data:/data/db
      # - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    env_file:
      - .env
    command: [ --auth ]
  redis:
    container_name: recipe-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis
    env_file:
      - .env
    command: [ "--requirepass ${REDIS_PASSWORD}" ]
  redis-insight:
    container_name: redis-insight
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - "8001:8001"
    links:
      - redis
volumes:
  mongodb-data:
  redis-data:
